const projects = [    
    {
        "name": "NotifyText",
        "shortName": "NotifyText",
        "headline": "Full Stack Application Web",
        "caption": "React + Bootstrap Frontend Webpage dedicated to setting reminders, and sending notifications for scheduled events to a custom destination. Extensive form allows user to input phone number to send a custom message message. Express, Postgres, Sequelize, and Twilio are utilized in the backend. Backend allows for user to create, read, update, and delete content. Uses multiple backend associations.",
        "hasGithub": true,
        "githubrepo": "https://github.com/KevinWithrow/SleekForum",
        "hassite": "hidden",
        "site": "",
        "gif": "notext.gif",
        "tags": {"html5/css": true, "bootstrap": true, "handlebars":true, "expressjs":true, "postgres":true }
    },
    {
        "name": "Fullstack Authentication",
        "shortName": "Fullstack Authentication",
        "headline": "Full Stack Frameworks",
        "caption": "React + Sequelize powered web application that serves as the frame for a website. Featuring custom React Hooks to manage authorization for protected URL. Allows for user to register for site, login/logout functionality. Allows for updating of user name/email/password. Express, Postgres, and Sequelize are utilized in the backend.",
        "hasGithub": true,
        "githubrepo": "https://github.com/qthibodeaux/Sidelined",
        "hassite": "hidden",
        "site": "",
        "gif": "fullauth.gif",
        "tags": {"html5/css": true, "bootstrap":true, "react":true, "redux":true }
    },
    {
        "name": "Mary's BBQ",
        "shortName": "Mary's BBQ",
        "headline": "Frontend Restraurant Web Application",
        "caption": "React + Bootstrap powered website for a mock restaurant, has a menu, cart, and allows for order.",
        "hasGithub": true,
        "githubrepo": "https://github.com/qthibodeaux/ReactFullStackSkeleton",
        "hassite": "hidden",
        "site": "",
        "gif": "marys.png",
        "tags": {"html5/css": true, "react":true, "expressjs":false, "postgres":false, "axios": false},
    },
    {
        "name": "Project Sidelined",
        "shortName": "Project Sidelined",
        "headline": "Frontend Interactive Cardgame",
        "caption": "Frontend creative entertainment application. Uses popular tv series as a basis for a card game. Uses React and Recoil for advanced  state management. Uses extensive javascript programming to management and manipulate data for card game interaction.",
        "hasGithub": true,
        "githubrepo": "https://github.com/qthibodeaux/DCFirstGroupProject",
        "hassite": "hidden",
        "site": "",
        "gif": "sideline.gif",
        "tags": {"html5/css" : true }
    },
    {
        "name": "Piano Connection",
        "shortName": "Piano Connection",
        "headline": "Frontend Website",
        "caption": "React + Grommet powered front end website for private piano company. Website to be used for information, discoverability, and online presence. Worked closely with Piano Connection to decide on styling, media, page content, and creation. First project working with professional third party.",
        "hasGithub": true,
        "githubrepo": "https://github.com/qthibodeaux/DCFirstGroupProject",
        "hassite": "hidden",
        "site": "",
        "gif": "piano.gif",
        "tags": {"html5/css" : true }
    },
]



const post = [
    {
        title: "ComponentLibraryConfusion!!!!!!!!!",
        image: "componentcrop.jpg",
        subtitle: "Eeny, meeny, miny, moe",
        p1: "This week’s update came a little later than I planned. I am currently juggling multiple projects that I am trying to finish. I don’t have an issue juggling the projects and I have done well with time management. I just have to remember that programming takes much longer than I think it is going to take. Even when I have it planned out, have my resources readily available, and reduce scope of the project, it will rarely come together as fast as I hope it is.",
        p2: "On that note, when I am comfortable and in my zone, I can crank out some code! I am getting pretty efficient in my comfort areas. I am happy with my progress in working with Bootstrap, React, Express, and knex. It is really encouraging and more than a sign that I can do it. But I know I can be great at this coding thing.",
        p3: "On the opposite side of that, I have to remember to push myself. Don’t just settle for doing the things I am good at. But to practice those new skills and become comfortable with those. It took some tooling to get comfortable with Bootstrap. I know my blindspots and will continue to improve. I am really grateful for the circle I have. My mentors continue to push me but remain great resources of knowledge when I am in a rut. ",
        p4: "Wrapping this up, I am excited for the projects I have coming up. The few solo projects are coming to a close. One is a major project that would’ve taken me WEEKS to finish earlier this year. I cranked out most of the code last weekend before the week’s task beat me up and delayed my progress. Soon I will also start collaborating with some of my bootcamp friends. Those guys are awesome and it’s fun to communicate and watch us grow together. ",
        p5: "",
        date: "October 1, 2020",
    },
    {
        title: "Be Someone",
        image: "besomeonecrop.jpg",
        subtitle: "",
        p1: "Excitement! Major site update. I decided to add a blog and update notes to my site. The purpose of my blog is to log my journey as a software developer and express my thoughts on my experience/journey. My personal site has undergone a few major revisions and will continue to do so. I have more ideas for what I want to do and will chronicle that here as I continue to develop in software development.",
        p2: "I have gotten so much more comfortable with React and Bootstrap. I am not fighting with alignments much anymore, which allows me to play around with javascript which is more my preference. I love backend equations and algorithms. Figuring out new and inventive ways to manipulate and change data is exciting. I like the challenge.",
        p3: "I have gotten back into C#, getting reacquainted with the language. It is like riding a bike. The transition back was not as hard as I thought. Even though it is a much more strictly typed language, it still feels familiar.",
        p4: "Planned site changes add recent projects I have been working on. That section is pretty sparse, so I definitely want to get that packed. Also, I want to flesh out the older projects. The gifs are nice but the dom manipulation or dynamic state changes needs to be put on full display. It will be fun implementing that into the site. ",
        p5: "Software development is fun. I’ve enjoyed the learning experience the past year. I want to continue to grow. I want to continue to challenge myself. I want to try to make some cool stuff. I want to Be Someone. If you’ve made it this far, thank you for reading. ",
        date: "September 24, 2020",
    },
]

const updates = [
    {date: "10 September 2021", content: "Complete Revamp Initiated"},
    {date: "17 September 2021 ", content: "Update: Added ReactFullStackSkeleton Project, updated Blog, and changed the updates tab."},
    {date: "21 September 2021 ", content: "Update: Addded tabs to main component. Three tabs for Projects, Blog, and Site Update. Added React component for each tab."},
]

const blags = [
    {
        title: "Be Someone",
        image: "besomeonecrop.jpg",
        subtitle: "",
        post: [
            "Excitement! Major site update. I decided to add a blog and update notes to my site. The purpose of my blog is to log my journey as a software developer and express my thoughts on my experience/journey. My personal site has undergone a few major revisions and will continue to do so. I have more ideas for what I want to do and will chronicle that here as I continue to develop in software development",
            "Excitement! Major site update. I decided to add a blog and update notes to my site. The purpose of my blog is to log my journey as a software developer and express my thoughts on my experience/journey. My personal site has undergone a few major revisions and will continue to do so. I have more ideas for what I want to do and will chronicle that here as I continue to develop in software development.",
            "Excitement! Major site update. I decided to add a blog and update notes to my site. The purpose of my blog is to log my journey as a software developer and express my thoughts on my experience/journey. My personal site has undergone a few major revisions and will continue to do so. I have more ideas for what I want to do and will chronicle that here as I continue to develop in software development."
        ],
        date: "September 24, 2020",
    },
    {
        title: "Organization",
        image: "organization.jpg",
        subtitle: "Making Decisions",
        post: [
            "I have narrowed down the tools that I want to use. Converting the legacy content to new Frameworks and technologies is no easy feat. My initial projects from the bootcamp were in a group and using HTML. The task i am placing upon myself is doing them by myself and with new tools.",
            "YIKES! I never said it would be easy. LOL. So, adding a backend to a project, choosing a backend, fleshing out ideas, using new methods I've learned, and many additions I want to make is exciting. For backend, I have not made a final decision on the tool I want to use.",
            "For front end, I have decided to use Grommet. I really thought about using Material UI or Bootstrap but I want to challenge myself a bit. And also, I love the components and tools in Grommet. The documentation makes sense to me. So I will begin to learn the nuances and give Grommet the kick in the butt to make it work for me! :D"
        ],
        date: "September 17, 2021",
    },
    {
        title: "Project Restart",
        image: "projectrestart.png",
        subtitle: "Massive Reamp",
        post: [
                "After taking time away from programming due to life circumstances and work, I have decided to dedicate time to really improving my craft starting with my website. I have done a personal site before, but I want my site to be a huge complication of all my projects. It is a daunting task I will take upon myself, because I want to update all legecy content with modern technolgy, tools, practices, and things I've learned since I've begun programming.",
                "The task will not be easy and will certainly be time consuming. But I know I will learn a along the way and really improve as I go along. A couple of things needs to happen before I can make all of it happen.",
                "So, I have my goal, knowledge of how I want to do it. I will begin by playing to my strengths. I will focus on origanization and coming up with an action plan. I am excited to see where this goes. Starting brand new!"
            ],
            date: "September 10, 2021",
    },

    
    
]

const quotes = [
{quote: "History has shown us that courage can be contagious, and hope can take on a life of its own. –Michelle Obamaquote"},
{quote: "The cost of liberty is less than the price of repression.” –  W.E.B. Du Bois"},
{quote: "Education is the most powerful weapon which you can use to change the world.” – Nelson Mandela"},
{quote: "In recognizing the humanity of our fellow beings, we pay ourselves the highest tribute.” – Thurgood Marshall"},
{quote: "Hate is too great a burden to bear. It injures the hater more than it injures the hated.” – Coretta Scott King"},
{quote: "Defining myself, as opposed to being defined by others, is one of the most difficult challenges I face.” – Carol Moseley-Braun"},
{quote: "A life is not important except in the impact it has on other lives.” – Jackie Robinson"},
{quote: "Every time you state what you want or believe, you’re the first to hear it. It’s a message to both you and others about what you think is possible. Don’t put a ceiling on yourself.” – Oprah Winfrey"},
{quote: "My humanity is bound up in yours, for we can only be human together.” – Desmond Tutu"},
{quote: "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.” – Martin Luther King Jr."},
{quote: "You can’t separate peace from freedom because no one can be at peace unless he has his freedom.” – Malcom X"},
{quote: "It isn’t where you come from; it’s where you’re going that counts.” – Ella Fitzgerald"},
{quote: "Character is power.” – Booker T. Washington"},
{quote: "If there is no struggle, there is no progress.” – Frederick Douglass"},
{quote: "Change will not come if we wait for some other person or some other time. We are the ones we’ve been waiting for. We are the change that we seek.” – Barack Obama"},
{quote: "I have learned over the years that when one’s mind is made up, this diminishes fear; knowing what must be done does away with fear.” – Rosa Parks"},
{quote: "The time is always right to do what is right.” – Martin Luther King, Jr."},
{quote: "Freedom is never given; it is won.” – A. Philip Randolph"},
{quote: "Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome while trying to succeed.” – Booker T. Washington"},
]

const pmondex = [
    {
        name: 'Squirtle',
        intro: 'https://c.tenor.com/mEJxSIEOYggAAAAC/pokemon-squirtle.gif',
        frontSprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png',
        backSprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/7.png',
        hoverDescription: 'The best choice you can make!',
        action1Name: 'Taunt',
        action1gif: 'https://c.tenor.com/1VBCLN765akAAAAC/pokemon-squirtle.gif',
        action1verb: 'Squirtle taunts you.',
        action2Name: 'Friendsgiving',
        action2gif: 'https://c.tenor.com/D5YmMILtEDAAAAAd/daps-homies.gif',
        action2verb: 'Squirtle calls his friends.',
        action3Name: 'Totes Adorbs!',
        action3gif: 'https://c.tenor.com/GvSAFDzGxa4AAAAd/squirtle-squirtle-squad.gif',
        action3verb: 'Squirtle used undeniable CUTENESS!',
        action4Name: 'Roast',
        action4gif: 'https://c.tenor.com/hFqgqcE1NZYAAAAC/pokemon-gang.gif',
        action4verb: 'Squirtle roast you, and his friends laugh at you.',
        death: 'https://c.tenor.com/M49TybebIFcAAAAC/sad-crying.gif',
    },
    {
        name: 'Bulbasaur',
        intro: 'https://c.tenor.com/38wTyIwrukEAAAAC/bulbasaur.gif',
        frontSprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png',
        backSprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/1.png',
        hoverDescription: 'The best choice you can make!',
        action1Name: 'Befriend!',
        action1gif: 'https://c.tenor.com/q5S22chrWk4AAAAC/squirtle-comfort.gif',
        action1verb: 'Did we just become best friends?',
        action2Name: 'Trampoline',
        action2gif: 'https://c.tenor.com/hL-17Wli6tYAAAAd/blubasaur-pokemon.gif',
        action2verb: 'Bulbasaur jumps off of your head!',
        action3Name: 'High Five!',
        action3gif: 'https://c.tenor.com/vb1I0DwVg_AAAAAC/pokemon-bulbasaur.gif',
        action3verb: 'Bulasaur used high five!',
        action4Name: 'Bulbanato',
        action4gif: 'https://c.tenor.com/EMORr7WIiagAAAAC/bulbasaur-razorleaf.gif',
        action4verb: 'Bulbasaur created a tornado..it was very effective.',
        death: 'https://c.tenor.com/lAMA4S83dREAAAAC/bulbasaur-pokemon.gif',
    },
    {
        name: 'Charmander',
        intro: 'https://c.tenor.com/EM8H5OXABPUAAAAC/charmander-pokemon.gif',
        frontSprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png',
        backSprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/4.png',
        hoverDescription: 'The best choice you can make!',
        action1Name: 'Intimidate',
        action1gif: 'https://c.tenor.com/E-6b0MYrfKoAAAAC/pokemon-ash.gif',
        action1verb: 'Charmander laughs at you.',
        action2Name: 'Sleep',
        action2gif: 'https://c.tenor.com/yd_cLAIoegoAAAAC/charmander-pokemon.gif',
        action2verb: 'Charmander is bored of your shenanigans.',
        action3Name: 'Charbroiled!',
        action3gif: 'https://c.tenor.com/14F2_e6M_iYAAAAC/fire-pokemon.gif',
        action3verb: 'Charmander breathes hot fire!',
        action4Name: 'Beauty Nap!',
        action4gif: 'https://c.tenor.com/1jKel8wNBxwAAAAC/charmander-pokemon.gif',
        action4verb: 'Charmander is tired from being this hot!',
        death: 'https://c.tenor.com/V-6ZF3wyefwAAAAC/charmander-pokemon.gif',
    },
    {
        name: 'Snorlax',
        intro: 'https://c.tenor.com/DMpbzFxAxRYAAAAd/snorlax.gif',
        frontSprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/143.png',
        backSprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/143.png',
        hoverDescription: 'The best choice you can make!',
        action1Name: 'Zzzz',
        action1gif: 'https://c.tenor.com/q5aOIZTUq24AAAAC/snorlax-pokemon.gif',
        action1verb: 'Zzzz',
        action2Name: 'ZzzzZZZ',
        action2gif: 'https://c.tenor.com/zTTDnOPOVJ8AAAAC/sleepy-snorlax.gif',
        action2verb: 'ZzzzZZZ',
        action3Name: 'ZzzzZZZzzz!',
        action3gif: 'https://c.tenor.com/X1dGurSfwzUAAAAd/snorlax-roll.gif',
        action3verb: 'ZzzzZZZzzz',
        action4Name: 'Awaken, my love!',
        action4gif: 'https://c.tenor.com/L8dp0-pg9g8AAAAC/snorlax-good-morning.gif',
        action4verb: 'Snorlax is awake!',
        death: 'https://c.tenor.com/htjYFNrNZzQAAAAC/yawn-snorlax.gif',
    },
    {
        name: 'Eevee',
        intro: 'https://c.tenor.com/dWEH-rTDNmQAAAAC/eevee-cute.gif',
        frontSprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/133.png',
        backSprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/133.png',
        hoverDescription: 'The best choice you can make!',
        action1Name: 'Seeing stars!',
        action1gif: 'https://c.tenor.com/dfxlpQNm8GgAAAAC/eevee-pokemon.gif',
        action1verb: 'Eevee over powers you with cuteness!',
        action2Name: 'Smile',
        action2gif: 'https://c.tenor.com/uB7UhNYUPWoAAAAC/eevee-smiles.gif',
        action2verb: 'Eevee  smiles and steals your heart<3!',
        action3Name: 'Dance!',
        action3gif: 'https://c.tenor.com/eYsmB_AxDRkAAAAC/eevee-pokemon.gif',
        action3verb: 'Eevee used dancing machine.',
        action4Name: 'Weeeeeeeee',
        action4gif: 'https://c.tenor.com/ETOCjrFd4AoAAAAC/pokemon-eevee.gif',
        action4verb: 'Eevee used slide.',
        death: 'https://c.tenor.com/_LsL6HZuWdMAAAAC/pokemon-eevee.gif',
    },
    {
        name: 'Gengar',
        intro: 'https://c.tenor.com/Cy-XR7xr-kYAAAAC/gengar-jumping.gif',
        frontSprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/94.png',
        backSprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/94.png',
        hoverDescription: 'The best choice you can make!',
        action1Name: 'Ethereal Snicker',
        action1gif: 'https://c.tenor.com/zyd3laUFPGsAAAAC/gengar-pokemon.gif',
        action1verb: 'Gengar and friends laugh at their opponent.',
        action2Name: 'Dance',
        action2gif: 'https://c.tenor.com/RCz8rA8vE-wAAAAC/gengar-gengar-pokemon.gif',
        action2verb: 'Gengar bust out some serious dance moves.',
        action3Name: 'Trance',
        action3gif: 'https://c.tenor.com/9bCkYdfRgigAAAAC/gengar-ghost.gif',
        action3verb: 'Gengar uses trance.',
        action4Name: 'Poot',
        action4gif: 'https://c.tenor.com/hlrCj-B1xgwAAAAC/gengar-wave.gif',
        action4verb: 'Gengar releases some ghostly gas',
        death: 'https://c.tenor.com/Cl5Rvhh7DhMAAAAd/gengar.gif',
    },
    {
        name: 'Pikachu',
        intro: 'https://c.tenor.com/DduO0vCQRM0AAAAC/excited-excited-pikachu.gif',
        frontSprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png',
        backSprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/25.png',
        hoverDescription: 'The best choice you can make!',
        action1Name: 'Cheer',
        action1gif: 'https://c.tenor.com/SKwR5Try0V4AAAAC/get-well.gif',
        action1verb: 'Pikechu cheers his friends up',
        action2Name: 'Smooches',
        action2gif: 'https://c.tenor.com/XNgh06B3I_gAAAAC/pokemon-cute.gif',
        action2verb: 'Pikachu puckers up!',
        action3Name: 'Multiply',
        action3gif: 'https://c.tenor.com/qObvHG4rT28AAAAC/pikachu-pokemon.gif',
        action3verb: 'Why are there so many Pikachu?',
        action4Name: 'Astonish',
        action4gif: 'https://c.tenor.com/UZJd1pjj4NMAAAAC/surprised-pikachu.gif',
        action4verb: 'Pikachu is so amazing, even he cant believe it!',
        death: 'https://c.tenor.com/CFNA9X91BIwAAAAC/pikachu-pokemon.gif',
    },
    {
        name: 'Jigglypuff',
        intro: 'https://c.tenor.com/iz_zwelJixkAAAAC/pokemon-jigglypuff.gif',
        frontSprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png',
        backSprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/39.png',
        hoverDescription: 'The best choice you can make!',
        action1Name: 'Hot air',
        action1gif: 'https://c.tenor.com/Wmi416Of3HMAAAAC/jigglypuff-pokemon.gif',
        action1verb: 'Jigglypuff is UPSET!',
        action2Name: 'Letter',
        action2gif: 'https://c.tenor.com/oIbegxZLLoYAAAAC/jigglypuff-hmph.gif',
        action2verb: 'Jigglypuff writes a very stern letter to the manager!',
        action3Name: 'GASP',
        action3gif: 'https://c.tenor.com/DVUNLw7fhOoAAAAC/jigglypuff-oups.gif',
        action3verb: 'Jigglypuff can NOT believe it!',
        action4Name: 'Assault',
        action4gif: 'https://c.tenor.com/KqJ03qXwT0oAAAAd/jigglypuff-kick.gif',
        action4verb: 'Jigglypuff is TIRED and goes on the offensive!',
        death: 'https://c.tenor.com/zEPNBUyFHukAAAAC/jigglypuff.gif',
    },
    {
        name: 'Margikarp',
        intro: 'https://c.tenor.com/6R024amtVhgAAAAC/pokemon-magikarp.gif',
        frontSprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/129.png',
        backSprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/129.png',
        hoverDescription: 'The best choice you can make!',
        action1Name: 'Splash',
        action1gif: 'https://c.tenor.com/6R024amtVhgAAAAC/pokemon-magikarp.gif',
        action1verb: 'Magikarp used splash, its not very effective.',
        action2Name: 'Splash',
        action2gif: 'https://c.tenor.com/6R024amtVhgAAAAC/pokemon-magikarp.gif',
        action2verb: 'Magikarp used splash, its not very effective.',
        action3Name: 'Splash',
        action3gif: 'https://c.tenor.com/6R024amtVhgAAAAC/pokemon-magikarp.gif',
        action3verb: 'Magikarp used splash, its not very effective.',
        action4Name: 'Splash',
        action4gif: 'https://c.tenor.com/6R024amtVhgAAAAC/pokemon-magikarp.gif',
        action4verb: 'Magikarp used splash, its not very effective.',
        death: 'https://c.tenor.com/6R024amtVhgAAAAC/pokemon-magikarp.gif',
    },
    {
        name: 'Meowth',
        intro: 'https://c.tenor.com/6R024amtVhgAAAAC/pokemon-magikarp.gif',
        frontSprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/52.png',
        backSprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/52.png',
        hoverDescription: 'The best choice you can make!',
        action1Name: 'Action',
        action1gif: 'https://c.tenor.com/F68hiHJzCsQAAAAC/meowth.gif',
        action1verb: 'Meowth gets ready!',
        action2Name: 'Beat',
        action2gif: 'https://c.tenor.com/WD8djonb1JsAAAAC/team-rocket-pokemon.gif',
        action2verb: 'Meowth drops a sick beat!',
        action3Name: 'Rain',
        action3gif: 'https://c.tenor.com/sTn876bIuyEAAAAC/pokemon-meowth.gif',
        action3verb: 'Meowth makes it rain!',
        action4Name: 'Splash',
        action4gif: 'https://c.tenor.com/6R024amtVhgAAAAC/pokemon-magikarp.gif',
        action4verb: 'Magikarp used splash, its not very effective.',
        death: 'https://c.tenor.com/6yv34d_NXM0AAAAC/pokemon-chronicles-pokemon.gif',
    },
    {
        name: 'Charizard',
        intro: 'https://c.tenor.com/6R024amtVhgAAAAC/pokemon-magikarp.gif',
        frontSprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png',
        backSprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/6.png',
        hoverDescription: 'The best choice you can make!',
        action1Name: 'Inferno',
        action1gif: 'https://c.tenor.com/I-GBbHpc4jIAAAAC/charizard-flamethrower.gif',
        action1verb: 'Charizard is just getting warmed up!',
        action2Name: 'Inferno',
        action2gif: 'https://c.tenor.com/cnw12Xbe1x0AAAAC/charizard-flamethrower.gif',
        action2verb: 'Charizard spits hot fire!',
        action3Name: 'Inferno',
        action3gif: 'https://c.tenor.com/mEbl5WtmqyMAAAAC/charizard-pokemon-charizard.gif',
        action3verb: 'Charizard spits hot fire!',
        action4Name: 'Splash',
        action4gif: 'https://c.tenor.com/6R024amtVhgAAAAC/pokemon-magikarp.gif',
        action4verb: 'Magikarp used splash, its not very effective.',
        death: 'https://c.tenor.com/V892f2zI0fgAAAAC/pokemon-charizard.gif',
    },
    {
        name: 'Mewtwo',
        intro: 'https://c.tenor.com/6R024amtVhgAAAAC/pokemon-magikarp.gif',
        frontSprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/150.png',
        backSprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/150.png',
        hoverDescription: 'The best choice you can make!',
        action1Name: 'Haduken',
        action1gif: 'https://c.tenor.com/7q2AtSx5r08AAAAC/pokemon-mewtwo.gif',
        action1verb: 'HADUKEEEN.',
        action2Name: 'Splash',
        action2gif: 'https://c.tenor.com/esaTulyVSNEAAAAC/mewtwo.gif',
        action2verb: 'Mewtwo launches psych barrage! ',
        action3Name: 'Peer',
        action3gif: 'https://c.tenor.com/wMVx5F4f6rIAAAAC/pokemon-mewtwo.gif',
        action3verb: 'Mewtwo peers into your soul and is not pleased.',
        action4Name: 'Splash',
        action4gif: 'https://c.tenor.com/6R024amtVhgAAAAC/pokemon-magikarp.gif',
        action4verb: 'Magikarp used splash, its not very effective.',
        death: 'https://c.tenor.com/6R024amtVhgAAAAC/pokemon-magikarp.gif',
    },
    {
        teamRocket: 'https://c.tenor.com/CiCi7ZMCyDsAAAAC/team-rocket-meowth.gif'
    }
]

export { post, projects, updates, blags, quotes, pmondex }